### ISSUE TITLE
No categories in feed

### ISSUE THREAD

**Issue by house92** [bookwhen/opendata#5]
There aren't any activity categories present in your feed, which are necessary for your data to be displayed properly on front-ends using our API. Could you please add this as a field?

**Comment by gregjoy1** [comment]
Hi Sam,
Thanks for your interest in Bookwhen's OpenActive feed. Which feed are you referring to? 
https://bookwhen.com/api/openactive/events

or

https://bookwhen.com/api/openactive/event_types

The `event_types` feed does have a `category` field but not all events in Bookwhen have these categories so we are limited in what we publish and everything we have already is in the pre-existing field.

Hope this helps?
