### ISSUE TITLE
Availability information shown on website but not in feed

### ISSUE THREAD

**Issue by house92** [bookwhen/opendata#7]
Although the sessions on your website state how many spaces are left, there seems to be only a field for sessions capacity in your feed. Would you be able to share this information through your open data feed?

**Comment by gregjoy1** [comment]
Hi Sam,
We publish the remaining space count in our `events` feed (https://bookwhen.com/api/openactive/events) inside of the `remainingAttendeeCapacity` field.
Hope this helps?

**Comment by gregjoy1** [comment]
We also dont show remaining attendee counts for recurring events as we cannot get that out of Bookwhen because these are extrapolated from recurrence rules.
